format = """
$hostname\
[](fg:blue bg:yellow)\
$directory\
[](fg:yellow bg:purple)\
$git_branch\
$git_status\
[](purple)
$character"""

[hostname]
ssh_only = false
format = '[ 󰀶 $user@$ssh_symbol$hostname ](bg:blue)'

[directory]
format = "[ $path ](bg:yellow)"
truncation_length = 10
home_symbol = "~"
truncation_symbol = "…/"

[character]
success_symbol = "[󰘍 ](bold green)"
error_symbol = "[x](bold red)"

[username]
format = "[$user](bold blue)[ - ](red)"
disabled = false
show_always = true

[git_branch]
symbol = " "
format = '[ $symbol$branch(:$remote_branch) ](bg:purple)'

[git_status]
format = '[$all_status$ahead_behind ](bg:purple)'
modified = "!$count"
untracked = "?$count"
stashed = "󰆦 !"
ahead = "↑$count"
behind = "↓$count"

[cmd_duration]
disabled = true

[aws]
disabled = true

[nodejs]
detect_files = ['package.json', '.node-version', '!bun.lockb']

