alias config="bbedit ~/dotfiles"
alias nv="open -a Nova"
alias ptob="gh pr create -B beta"
alias prune-git="git remote prune origin"
alias dev="sh ~/dotfiles/scripts/run-dev.sh"
alias lint="sh ~/dotfiles/scripts/run-lint.sh"
alias commit="sh ~/dotfiles/scripts/git-commit-push.sh"
alias macmini="ssh admin@Memory-Alpha.local"
alias ls="eza"
alias cd="z"
alias runx="npx concurrently \"serverless offline\" \"nx dev frontend\""
alias brewfile="brew bundle dump --file=~/dotfiles/Brewfile --force"
