if [ "$TERM_PROGRAM" != "Apple_Terminal" ]; then
	eval "$(oh-my-posh init zsh --config ~/dotfiles/misc_config/ohmyposh.json)"
fi

source $(brew --prefix nvm)/nvm.sh

# Load seperated config files
for conf in "$HOME/dotfiles/zsh_config/"*.zsh; do
  source "${conf}"
done
unset conf

[[ "$TERM_PROGRAM" == "CodeEditApp_Terminal" ]] && . "/Applications/CodeEdit.app/Contents/Resources/codeedit_shell_integration.zsh"


eval $(thefuck --alias)
eval "$(zoxide init zsh)"
# eval "$(starship init zsh)"
eval "$(atuin init zsh)"

# bun completions
[ -s "/Users/ghall/.bun/_bun" ] && source "/Users/ghall/.bun/_bun"
